ccflags-y := -Idrivers/video/msm

obj-$(CONFIG_FB_MSM_LCDC_LD9040_WVGA) += lcdc_ld9040.o
obj-$(CONFIG_FB_MSM_LCDC_LD9040_WVGA) += smart_dimming_ea8868.o
obj-$(CONFIG_FB_MSM_MIPI_DSI_S6E8AA0_WXGA_Q1) += mipi_s6e8aa0_wxga_q1.o
obj-$(CONFIG_FB_MSM_MIPI_DSI_S6E8AA0_WXGA_Q1) += smart_dimming.o
obj-$(CONFIG_FB_MSM_MIPI_DSI_ESD_REFRESH) += sec_mipi_lcd_esd_refresh.o
