obj-$(CONFIG_TARGET_SERIES_CELOX) += board-celox.o
obj-$(CONFIG_TARGET_SERIES_CELOX) += board-celox-display.o
obj-$(CONFIG_TARGET_SERIES_CELOX) += board-celox-gpiomux.o
obj-$(CONFIG_TARGET_SERIES_CELOX) += board-celox-keypad.o
obj-$(CONFIG_TARGET_SERIES_CELOX) += board-celox-pmic.o
obj-$(CONFIG_TARGET_SERIES_CELOX) += board-celox-regulator.o
obj-$(CONFIG_TARGET_SERIES_CELOX) += board-celox-storage.o

