#
# Makefile for the wacom drivers.
#

obj-$(CONFIG_EPEN_WACOM_G5SP) += wacom_i2c.o
obj-$(CONFIG_EPEN_WACOM_G5SP) += wacom_i2c_firm.o
obj-$(CONFIG_EPEN_WACOM_G5SP) += wacom_i2c_flash.o
obj-$(CONFIG_EPEN_WACOM_G5SP) += wacom_i2c_func.o
